name: Regenerate the plugin docs code
on:
  schedule:
    # run a bit before midnight when go deps change
    - cron: '0 23 * * *'

  # allow manual triggering
  workflow_dispatch: {}
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://golang:1.15
        name: Regenerate the plugins docs
        env:
          GIT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
          DISABLE_COMMMIT: disable
        with:
          entrypoint: ./regen-plugins.sh
      - name: create-pr
        uses: ./.github/actions/create-pr-for-plugin-docs
        with:
          token: ${{ secrets.GIT_BOT_TOKEN }}
          run_id: ${{ github.run_id }}
